#platform.team@lge.com	2011.01

EXTRA_CFLAGS += -Iarch/arm/mach-msm
EXTRA_CFLAGS += -Iarch/arm/mach-msm/qdsp6v2
EXTRA_CFLAGS += -Ilge/include

obj-$(CONFIG_MACH_LGE_C1_BOARD_SPR)	+= board_cayman_sprint.o
#[LG_BTUI] To seperate bt power driver module form All in One board configuration  minwoo2.kim@lge.com
obj-$(CONFIG_MACH_LGE_C1_BOARD_SPR)	+= platform_cayman_sprint_bt.o
obj-$(CONFIG_MACH_LGE_C1_BOARD_SPR)	+= platform_cayman_sprint_camera.o
obj-$(CONFIG_MACH_LGE_C1_BOARD_SPR)	+= platform_cayman_sprint_input.o
#obj-$(CONFIG_MACH_LGE_C1_BOARD_SPR)	+= platform_cayman_sprint_misc.o
#obj-$(CONFIG_MACH_LGE_C1_BOARD_SPR)	+= platform_cayman_sprint_mmc.o
obj-$(CONFIG_MACH_LGE_C1_BOARD_SPR)	+= platform_cayman_sprint_panel.o
obj-$(CONFIG_MACH_LGE_C1_BOARD_SPR)	+= platform_cayman_sprint_snd.o
obj-$(CONFIG_MACH_LGE_C1_BOARD_SPR)	+= gpiomux_cayman_sprint.o
obj-$(CONFIG_MACH_LGE_C1_BOARD_SPR)	+= devices_cayman_sprint.o
